services:
  app:
    image: romsper/testing-playground-backend:latest
    environment:
      DATABASE_URL: jdbc:postgresql://database:5432/playground
    ports:
      - "1111:1111"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: playground
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data: